// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHpB0q_cH82iH-lJJrGCsiW8O1O1sxTEA',
    appId: '1:571934156463:web:1235f35b1ecbd91bef165a',
    messagingSenderId: '571934156463',
    projectId: 'asasa-ba607',
    authDomain: 'asasa-ba607.firebaseapp.com',
    storageBucket: 'asasa-ba607.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Ph_Glx-k_IWPbO2DkpS0-aGyMKOR9Ao',
    appId: '1:571934156463:android:64cede7d54683088ef165a',
    messagingSenderId: '571934156463',
    projectId: 'asasa-ba607',
    storageBucket: 'asasa-ba607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ubhvEgrBjSHzCTjZkoZv5xZSTnoypTY',
    appId: '1:571934156463:ios:6f936d489c87a355ef165a',
    messagingSenderId: '571934156463',
    projectId: 'asasa-ba607',
    storageBucket: 'asasa-ba607.appspot.com',
    iosClientId: '571934156463-dd25rhejsnrqqk3frff76niivueo6bmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ubhvEgrBjSHzCTjZkoZv5xZSTnoypTY',
    appId: '1:571934156463:ios:6f936d489c87a355ef165a',
    messagingSenderId: '571934156463',
    projectId: 'asasa-ba607',
    storageBucket: 'asasa-ba607.appspot.com',
    iosClientId: '571934156463-dd25rhejsnrqqk3frff76niivueo6bmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHpB0q_cH82iH-lJJrGCsiW8O1O1sxTEA',
    appId: '1:571934156463:web:1235f35b1ecbd91bef165a',
    messagingSenderId: '571934156463',
    projectId: 'asasa-ba607',
    authDomain: 'asasa-ba607.firebaseapp.com',
    storageBucket: 'asasa-ba607.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAHpB0q_cH82iH-lJJrGCsiW8O1O1sxTEA',
    appId: '1:571934156463:web:93c45cd32f4e028aef165a',
    messagingSenderId: '571934156463',
    projectId: 'asasa-ba607',
    authDomain: 'asasa-ba607.firebaseapp.com',
    storageBucket: 'asasa-ba607.appspot.com',
  );
}
